パッケージング・型ヒント関連の改善
unyacat/westjr pull request #5
Opened 2022-05-27 18:33 UTC by eggplants

主に型を強化しました。別プログラムから利用する際に便利です。

- setup.cfgでのパッケージング ac7751795e576fb181926757a713c26c8833f377
- APIレスポンスのTypedDictでの型付け 3cba9db99253629778d165198c8275cf9502738d
- testの追加 b6bad1f0d3ad387db5e602e3a0620c386ef1345b
- 型情報の提供のためのパッケージ情報追加 c2aa405379f661c202e2fe10e3fbfa53c2e35663
- mypy strict modeでの型付け 41773cc0c2fb6e885dfd56e1cd26e426981e2ab0 
- pre-commitの導入 4a3a0a20ba36bc7fe4ae95287acb4c46a9e68c26

2022-05-27 19:18 UTC, eggplants commented
https://github.com/eggplants/westjr/actions/runs/2398326107

2022-06-04 03:47 UTC, unyacat requested changes

2022-06-04 03:47 UTC, unyacat commented on setup.cfg
> +url = https://github.com/ueyacat/westjr
ueyacat -> unyacat です．(ややこしい名前でごめんなさい)

2022-06-04 04:16 UTC, eggplants commented on setup.cfg
> +url = https://github.com/ueyacat/westjr
修正しました… 8b81e1c

2022-06-04 04:36 UTC, unyacat commented on westjr/response_types/area_master.py
> +    display: int
classの形式に統一するいかがでしょうか

2022-06-04 04:38 UTC, eggplants commented on westjr/response_types/area_master.py
> +    display: int
これPythonくんが悪いんですが、`from`が`from ... import ...`とかぶっているので、classで書くとエラーになるんですよね…

2022-06-04 04:43 UTC, unyacat commented on westjr/response_types/area_master.py
> +    delayText: list[DelayTextItem_From | DelayTextItem_To]
クラス名は CamelCase で良いと思います

2022-06-04 04:46 UTC, unyacat commented on westjr/response_types/area_master.py
> +    display: int
なるほどです・・・・・・そこまでは読めていませんでした ありがとうございます

2022-06-04 04:47 UTC, eggplants commented on westjr/response_types/area_master.py
> +    display: int
https://peps.python.org/pep-0589/#alternative-syntax

2022-06-04 06:02 UTC, eggplants commented on westjr/response_types/area_master.py
> +    delayText: list[DelayTextItem_From | DelayTextItem_To]
f6c6eb8f3dd0dd4412f6b2492288f419333255c0

2022-06-04 09:09 UTC, unyacat approved these changes

2022-06-04 10:45 UTC, eggplants commented
𝙍𝙚𝙖𝙙𝙮 𝙩𝙤 𝙢𝙚𝙧𝙜𝙚...

2022-06-04 15:43 UTC, unyacat commented
本当に隅から隅までありがとうございます。𝙢𝙚𝙧𝙜𝙚します

2022-06-04 15:43 UTC, merged